version: '3.5'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper-1
    container_name: zookeeper-1
    ports:
      - "2181:2181"
    env_file:
      - zookeeper.env
    healthcheck:
      test: /bin/sh -c '[ \"imok\" = \"$$(echo ruok | nc -w 1 127.0.0.1 2181)\" ]' || exit 1
      interval: 1m
    volumes:
      - zookeeper-1-data:/var/lib/zookeeper/data/
      - zookeeper-1-log:/var/lib/zookeeper/log/

  kafka-1:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka-1
    container_name: kafka-1
    stop_grace_period: 5m
    depends_on:
      - zookeeper-1
    ports:
      - "9092:9092"
      - "29092:29092"
    env_file:
      - kafka.env
    volumes:
      - kafka-1-data:/var/lib/kafka/data/

volumes:
  zookeeper-1-data:
  zookeeper-1-log:
  kafka-1-data:

